import type { PrismaClient } from '@prisma/client';
import type pg from 'pg';
import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest';
import { createPrismaClient } from '../db/client.js';
import { connect, firstRow, testDatabaseUrl, truncateAll } from '../test/database.js';
import {
  type PaymentWorld,
  UUID,
  delay,
  insertBooking,
  insertPayment,
  logSink,
  mtnDelivery,
  mtnProvider,
  mtnStatusBody,
  seedWorld,
  stubProvider,
} from '../test/payment-fixtures.js';
import { PAYMENT_ATTEMPT_WINDOW_SECONDS, startBookingFeePayment } from './initiate.js';
import { type PaymentProvider, PaymentProviderError } from './provider.js';
import { receiveWebhook } from './webhooks.js';

/**
 * Starting a booking-fee payment (plan.md Task 16; spec §3.1 step 9;
 * data-model_v2.md §5.11, §6.2, §7.2), against real PostgreSQL with the provider
 * stubbed or pointed at a fake MTN.
 *
 * What is proven: the `payment` row -- `initiated`, `mtn_momo_direct`, its
 * `our_ref` generated by the database -- is committed and visible to another
 * connection BEFORE the provider hears a word, so a provider that throws, or MTN
 * unreachable at the very first HTTP call, still leaves the attempt on record;
 * the provider is handed exactly that `our_ref` and the booking's frozen fee.
 * Accepted, the row is `pending`; refused, unreachable or past the deadline, it
 * is `failed` with the reason, and the booking is untouched -- still
 * `pending_payment`, `hold_expires_at` identical to the millisecond. `amount_rwf`
 * is `booking_fee_rwf` exactly and never changes afterwards, not even when a
 * webhook settles it. A booking already paid, lapsed, expired, closed, free or
 * unknown starts nothing; an attempt still waiting inside the window blocks a
 * second prompt, and one outside it does not; and two taps at once make one
 * payment.
 */

let prisma: PrismaClient;
let raw: pg.Client;
let world: PaymentWorld;

beforeAll(async () => {
  prisma = createPrismaClient(testDatabaseUrl());
  raw = connect();
  await raw.connect();
});

afterAll(async () => {
  await truncateAll(raw);
  await prisma.$disconnect();
  await raw.end();
});

beforeEach(async () => {
  await truncateAll(raw);
  world = await seedWorld(prisma);
});

// --- Helpers ----------------------------------------------------------------------------

type PaymentRow = {
  id: string;
  booking_id: string;
  kind: string;
  provider: string;
  our_ref: string;
  provider_ref: string | null;
  method: string | null;
  amount_rwf: number;
  status: string;
  failure_reason: string | null;
  settled_at: Date | null;
};

/** Every payment, through the raw driver: another connection than the one the code under test used. */
async function payments(): Promise<PaymentRow[]> {
  const result = await raw.query<PaymentRow>(
    `SELECT id::text, booking_id::text, kind, provider, our_ref::text, provider_ref, method, amount_rwf, status, failure_reason, settled_at
       FROM payment ORDER BY initiated_at, id`,
  );
  return result.rows;
}

async function onlyPayment(): Promise<PaymentRow> {
  const rows = await payments();
  expect(rows).toHaveLength(1);
  return rows[0] as PaymentRow;
}

type BookingState = { status: string; hold_ms: string | null; confirmed_at: Date | null; access_token_hash: string | null; updated_at: Date };

async function bookingState(reference: string): Promise<BookingState> {
  const result = await raw.query<BookingState>(
    `SELECT status, (extract(epoch FROM hold_expires_at) * 1000000)::bigint::text AS hold_ms, confirmed_at, access_token_hash, updated_at
       FROM booking WHERE reference = $1`,
    [reference],
  );
  return firstRow(result);
}

function start(provider: PaymentProvider, reference: string, options: { timeoutMs?: number; payerPhone?: string } = {}) {
  return startBookingFeePayment(
    { prisma, provider, ...(options.timeoutMs === undefined ? {} : { timeoutMs: options.timeoutMs }) },
    { reference, method: 'momo_mtn', payerPhone: options.payerPhone ?? '+250788123456' },
  );
}

// --- Before the provider ------------------------------------------------------------------

describe('the payment row exists before the provider is called', () => {
  it('is committed as initiated, mtn_momo_direct, with a database-generated our_ref, when the provider is reached -- and the provider then throws', async () => {
    const booking = await insertBooking(prisma, world, { bookingFeeRwf: 19_500 });
    let seenByProvider: PaymentRow[] = [];
    const provider = stubProvider({
      initiate: async (request) => {
        seenByProvider = await payments();
        expect(request.ourRef).toBe(seenByProvider[0]?.our_ref);
        throw new Error('stubbed provider client failure');
      },
    });

    const result = await start(provider, booking.reference);

    expect(seenByProvider).toHaveLength(1);
    expect(seenByProvider[0]).toMatchObject({
      booking_id: booking.id,
      kind: 'booking_fee',
      provider: 'mtn_momo_direct',
      our_ref: expect.stringMatching(UUID),
      amount_rwf: 19_500,
      status: 'initiated',
      provider_ref: null,
      method: null,
      failure_reason: null,
    });
    expect(result).toStrictEqual({ status: 'provider_failed', ourRef: seenByProvider[0]?.our_ref, outcome: 'unavailable' });
    expect(await onlyPayment()).toMatchObject({ id: seenByProvider[0]?.id, status: 'failed', failure_reason: 'provider_unavailable: Error' });
  });

  it('is on record before the real MTN client makes its first HTTP call, which then fails', async () => {
    const booking = await insertBooking(prisma, world);
    const seenAtFirstCall: PaymentRow[][] = [];
    const urls: string[] = [];
    const provider = mtnProvider({
      fetch: (async (input: string) => {
        urls.push(String(input));
        seenAtFirstCall.push(await payments());
        throw new TypeError('fetch failed');
      }) as typeof fetch,
    });

    const result = await start(provider, booking.reference);

    expect(urls).toEqual(['https://mtn.test/collection/token/']);
    expect(seenAtFirstCall[0]).toHaveLength(1);
    expect(seenAtFirstCall[0]?.[0]).toMatchObject({ status: 'initiated', provider: 'mtn_momo_direct', our_ref: expect.stringMatching(UUID) });
    expect(result).toMatchObject({ status: 'provider_failed', outcome: 'unavailable' });
    expect(await onlyPayment()).toMatchObject({
      status: 'failed',
      failure_reason: 'provider_unavailable: MTN MoMo could not be reached: TypeError',
    });
  });

  it('sends MTN the our_ref the database generated, as X-Reference-Id', async () => {
    const booking = await insertBooking(prisma, world);
    const referenceIds: (string | null)[] = [];
    const provider = mtnProvider({
      fetch: (async (input: string, init?: RequestInit) => {
        if (String(input).endsWith('/collection/token/')) return new Response(JSON.stringify({ access_token: 't', expires_in: 3600 }));
        referenceIds.push(new Headers(init?.headers).get('X-Reference-Id'));
        return new Response(null, { status: 202 });
      }) as typeof fetch,
    });

    const result = await start(provider, booking.reference);

    const payment = await onlyPayment();
    expect(result).toStrictEqual({ status: 'started', ourRef: payment.our_ref });
    expect(referenceIds).toEqual([payment.our_ref]);
    expect(payment.status).toBe('pending');
  });

  it('hands the provider the frozen fee, the method, the phone, the kind and the reference', async () => {
    const booking = await insertBooking(prisma, world, { bookingFeeRwf: 23_457 });
    const provider = stubProvider();

    await start(provider, booking.reference, { payerPhone: '+250722000111' });

    expect(provider.initiated).toStrictEqual([
      {
        ourRef: (await onlyPayment()).our_ref,
        amountRwf: 23_457,
        method: 'momo_mtn',
        payerPhone: '+250722000111',
        kind: 'booking_fee',
        bookingReference: booking.reference,
      },
    ]);
  });

  it('records a provider that is not configured as a failed attempt', async () => {
    const booking = await insertBooking(prisma, world);

    const result = await start(mtnProvider({ credentials: false }), booking.reference);

    expect(result).toMatchObject({ status: 'provider_failed', outcome: 'unavailable' });
    expect((await onlyPayment()).failure_reason).toMatch(/^provider_unavailable: MTN MoMo is not configured/);
  });
});

// --- Outcomes -------------------------------------------------------------------------------

describe('what the provider answers', () => {
  it('accepted: the row is pending, the booking untouched', async () => {
    const booking = await insertBooking(prisma, world);
    const before = await bookingState(booking.reference);

    const result = await start(stubProvider(), booking.reference);

    const payment = await onlyPayment();
    expect(result).toStrictEqual({ status: 'started', ourRef: payment.our_ref });
    expect(payment).toMatchObject({ status: 'pending', failure_reason: null, provider_ref: null, amount_rwf: 20_000 });
    expect(await bookingState(booking.reference)).toStrictEqual(before);
  });

  it('accepted with the provider’s own id: it is stored as provider_ref', async () => {
    const booking = await insertBooking(prisma, world);

    await start(stubProvider({ initiate: async () => ({ outcome: 'accepted', providerRef: 'FLW-123' }) }), booking.reference);

    expect(await onlyPayment()).toMatchObject({ status: 'pending', provider_ref: 'FLW-123' });
  });

  it('rejected: the row is failed with the provider’s code, the booking untouched', async () => {
    const booking = await insertBooking(prisma, world);
    const before = await bookingState(booking.reference);

    const result = await start(stubProvider({ initiate: async () => ({ outcome: 'rejected', reason: 'PAYER_NOT_FOUND' }) }), booking.reference);

    const payment = await onlyPayment();
    expect(result).toStrictEqual({ status: 'provider_failed', ourRef: payment.our_ref, outcome: 'rejected' });
    expect(payment).toMatchObject({ status: 'failed', failure_reason: 'PAYER_NOT_FOUND' });
    expect(await bookingState(booking.reference)).toStrictEqual(before);
  });

  it('a PaymentProviderError: failed, quoting our own message', async () => {
    const booking = await insertBooking(prisma, world);

    await start(stubProvider({ initiate: async () => Promise.reject(new PaymentProviderError('MTN MoMo answered 503')) }), booking.reference);

    expect((await onlyPayment()).failure_reason).toBe('provider_unavailable: MTN MoMo answered 503');
  });

  it('any other error: failed, naming the error but never quoting it', async () => {
    const booking = await insertBooking(prisma, world);

    await start(stubProvider({ initiate: async () => Promise.reject(new RangeError('api key sk_live_123 leaked here')) }), booking.reference);

    expect((await onlyPayment()).failure_reason).toBe('provider_unavailable: RangeError');
  });

  it('a thrown non-Error: failed as provider_unavailable: error', async () => {
    const booking = await insertBooking(prisma, world);

    await start(stubProvider({ initiate: async () => Promise.reject('just a string') }), booking.reference);

    expect((await onlyPayment()).failure_reason).toBe('provider_unavailable: error');
  });

  it('stores a rejection reason with a NUL character, and one of 10,000 characters, cut to 500', async () => {
    const nul = await insertBooking(prisma, world);
    await start(stubProvider({ initiate: async () => ({ outcome: 'rejected', reason: `BAD${String.fromCharCode(0)}CODE` }) }), nul.reference);
    const long = await insertBooking(prisma, world);
    await start(stubProvider({ initiate: async () => ({ outcome: 'rejected', reason: 'X'.repeat(10_000) }) }), long.reference);

    const [first, second] = await payments();
    expect(first?.failure_reason).toBe(`BAD${String.fromCharCode(0xfffd)}CODE`);
    expect(second?.failure_reason).toBe('X'.repeat(500));
  });

  it('never moves a row a webhook has already settled while the provider was answering', async () => {
    const accepted = await insertBooking(prisma, world);
    await start(
      stubProvider({
        initiate: async (request) => {
          await raw.query(`UPDATE payment SET status = 'succeeded', settled_at = now() WHERE our_ref = $1`, [request.ourRef]);
          return { outcome: 'accepted', providerRef: 'LATE-REF' };
        },
      }),
      accepted.reference,
    );
    const refused = await insertBooking(prisma, world);
    await start(
      stubProvider({
        initiate: async (request) => {
          await raw.query(`UPDATE payment SET status = 'pending' WHERE our_ref = $1`, [request.ourRef]);
          throw new Error('late failure');
        },
      }),
      refused.reference,
    );

    const [first, second] = await payments();
    expect(first).toMatchObject({ status: 'succeeded', provider_ref: null });
    expect(second).toMatchObject({ status: 'pending', failure_reason: null });
  });
});

// --- Timeout ---------------------------------------------------------------------------------

describe('a provider that does not answer in time', () => {
  it('leaves the row failed with failure_reason provider_timeout, the booking pending_payment and its hold identical', async () => {
    const booking = await insertBooking(prisma, world);
    const before = await bookingState(booking.reference);
    const began = Date.now();

    const result = await start(stubProvider({ initiate: () => new Promise(() => {}) }), booking.reference, { timeoutMs: 50 });

    expect(Date.now() - began).toBeLessThan(5_000);
    const payment = await onlyPayment();
    expect(result).toStrictEqual({ status: 'provider_failed', ourRef: payment.our_ref, outcome: 'unavailable' });
    expect(payment).toMatchObject({ status: 'failed', failure_reason: 'provider_timeout', amount_rwf: 20_000 });

    const after = await bookingState(booking.reference);
    expect(after.status).toBe('pending_payment');
    expect(after.hold_ms).not.toBeNull();
    expect(after.hold_ms).toBe(before.hold_ms);
    expect(after).toStrictEqual(before);
  });

  it('aborts the provider’s signal at the deadline', async () => {
    const booking = await insertBooking(prisma, world);
    let signal: AbortSignal | undefined;

    await start(
      stubProvider({
        initiate: (_request, given) => {
          signal = given;
          return new Promise((_resolve, reject) => given.addEventListener('abort', () => reject(new Error('aborted'))));
        },
      }),
      booking.reference,
      { timeoutMs: 50 },
    );

    expect(signal?.aborted).toBe(true);
    expect((await onlyPayment()).failure_reason).toBe('provider_timeout');
  });

  it('is a timeout with the real MTN client whose HTTP call hangs until aborted', async () => {
    const booking = await insertBooking(prisma, world);
    const provider = mtnProvider({
      fetch: ((_input: string, init?: RequestInit) =>
        new Promise<Response>((_resolve, reject) => {
          init?.signal?.addEventListener('abort', () => reject(new DOMException('This operation was aborted', 'AbortError')));
        })) as typeof fetch,
    });

    const result = await start(provider, booking.reference, { timeoutMs: 50 });

    expect(result).toMatchObject({ status: 'provider_failed', outcome: 'unavailable' });
    expect((await onlyPayment()).failure_reason).toBe('provider_timeout');
    expect((await bookingState(booking.reference)).status).toBe('pending_payment');
  });

  it('stays failed when the provider accepts after the deadline', async () => {
    const booking = await insertBooking(prisma, world);

    await start(
      stubProvider({
        initiate: async () => {
          await delay(200);
          return { outcome: 'accepted', providerRef: null };
        },
      }),
      booking.reference,
      { timeoutMs: 20 },
    );
    await delay(300);

    expect(await onlyPayment()).toMatchObject({ status: 'failed', failure_reason: 'provider_timeout' });
  });

  it('frees the booking to try again at once', async () => {
    const booking = await insertBooking(prisma, world);
    await start(stubProvider({ initiate: () => new Promise(() => {}) }), booking.reference, { timeoutMs: 20 });

    const retry = await start(stubProvider(), booking.reference);

    expect(retry.status).toBe('started');
    expect((await payments()).map((payment) => payment.status)).toEqual(['failed', 'pending']);
  });
});

// --- The amount ------------------------------------------------------------------------------

describe('amount_rwf', () => {
  it('equals booking_fee_rwf exactly, never the package price, a total, or a recomputed 40%', async () => {
    // 40% of 50,000 is 20,000; the frozen fee says otherwise, and wins.
    const booking = await insertBooking(prisma, world, { bookingFeeRwf: 17_777 });

    await start(stubProvider(), booking.reference);

    expect((await onlyPayment()).amount_rwf).toBe(17_777);
  });

  it('is unchanged after the webhook confirms the booking, and after the catalogue price changes', async () => {
    const booking = await insertBooking(prisma, world, { bookingFeeRwf: 19_500 });
    const provider = mtnProvider({
      fetch: (async (input: string) =>
        String(input).endsWith('/collection/token/')
          ? new Response(JSON.stringify({ access_token: 't', expires_in: 3600 }))
          : new Response(null, { status: 202 })) as typeof fetch,
    });
    const started = await start(provider, booking.reference);
    if (started.status !== 'started') throw new Error(`Expected started, got ${started.status}`);

    await prisma.package.update({ where: { id: world.packageId }, data: { priceRwf: 99_000 } });
    const outcome = await receiveWebhook(
      { prisma, log: logSink().log },
      provider,
      mtnDelivery(provider, started.ourRef, mtnStatusBody(started.ourRef, 'SUCCESSFUL', { amount: '19500' })),
    );

    expect(outcome.status).toBe('applied');
    expect(await onlyPayment()).toMatchObject({ status: 'succeeded', amount_rwf: 19_500 });
    expect((await bookingState(booking.reference)).status).toBe('confirmed');
  });

  it('is unchanged after a failure', async () => {
    const booking = await insertBooking(prisma, world, { bookingFeeRwf: 19_500 });
    await start(stubProvider({ initiate: async () => ({ outcome: 'rejected', reason: 'X' }) }), booking.reference);
    expect((await onlyPayment()).amount_rwf).toBe(19_500);
  });
});

// --- Nothing started ------------------------------------------------------------------------

describe('a booking that cannot be paid starts nothing', () => {
  async function expectNothingStarted(provider: ReturnType<typeof stubProvider>, paymentsBefore: number) {
    expect(provider.initiated).toEqual([]);
    expect(await payments()).toHaveLength(paymentsBefore);
  }

  it('not_found for an unknown reference', async () => {
    const provider = stubProvider();
    await expect(start(provider, 'BKY-2610-ZZZZZ')).resolves.toStrictEqual({ status: 'not_found' });
    await expectNothingStarted(provider, 0);
  });

  it('already_paid for a confirmed booking with a succeeded booking fee', async () => {
    const booking = await insertBooking(prisma, world, { status: 'confirmed' });
    await insertPayment(prisma, booking.id, { status: 'succeeded' });
    const provider = stubProvider();

    await expect(start(provider, booking.reference)).resolves.toStrictEqual({ status: 'already_paid' });
    await expectNothingStarted(provider, 1);
  });

  it('already_paid, not hold_expired, even when the booking still holds its slot', async () => {
    const booking = await insertBooking(prisma, world);
    await insertPayment(prisma, booking.id, { status: 'succeeded' });
    const provider = stubProvider();

    await expect(start(provider, booking.reference)).resolves.toStrictEqual({ status: 'already_paid' });
    await expectNothingStarted(provider, 1);
  });

  it('not already_paid for a booking whose only succeeded payment is a session fee', async () => {
    const booking = await insertBooking(prisma, world);
    await insertPayment(prisma, booking.id, { status: 'succeeded', kind: 'session_fee' });

    await expect(start(stubProvider(), booking.reference)).resolves.toMatchObject({ status: 'started' });
  });

  it.each([
    ['a lapsed hold on a booking the sweeper has not reached', { status: 'pending_payment', holdMinutes: -1 }],
    ['a pending_payment booking with no hold at all', { status: 'pending_payment', holdMinutes: null }],
    ['an expired booking', { status: 'expired' }],
    ['a confirmed booking with no succeeded fee', { status: 'confirmed' }],
    ['a completed booking', { status: 'completed' }],
    ['a no-show', { status: 'no_show' }],
    ['a booking the client cancelled', { status: 'cancelled_by_client' }],
    ['a booking the photographer cancelled', { status: 'cancelled_by_admin' }],
    ['an expired booking whose hold column still reads live', { status: 'expired', holdMinutes: 30 }],
  ])('hold_expired for %s', async (_case, seed) => {
    const booking = await insertBooking(prisma, world, seed);
    const provider = stubProvider();

    await expect(start(provider, booking.reference)).resolves.toStrictEqual({ status: 'hold_expired' });
    await expectNothingStarted(provider, 0);
  });

  it('nothing_to_pay for a zero booking fee, which a payment row cannot hold', async () => {
    const booking = await insertBooking(prisma, world, { bookingFeeRwf: 0 });
    const provider = stubProvider();

    await expect(start(provider, booking.reference)).resolves.toStrictEqual({ status: 'nothing_to_pay' });
    await expectNothingStarted(provider, 0);
  });
});

// --- One prompt at a time ---------------------------------------------------------------------

describe('an attempt still waiting on the payer', () => {
  it.each(['initiated', 'pending'])('blocks a new one while %s inside the window, answering its our_ref', async (status) => {
    const booking = await insertBooking(prisma, world);
    const waiting = await insertPayment(prisma, booking.id, { status, ageSeconds: PAYMENT_ATTEMPT_WINDOW_SECONDS - 10 });
    const provider = stubProvider();

    await expect(start(provider, booking.reference)).resolves.toStrictEqual({ status: 'in_progress', ourRef: waiting.ourRef });
    expect(provider.initiated).toEqual([]);
    expect(await payments()).toHaveLength(1);
  });

  it('answers the most recent waiting attempt when there are several', async () => {
    const booking = await insertBooking(prisma, world);
    await insertPayment(prisma, booking.id, { status: 'pending', ageSeconds: 120 });
    const newest = await insertPayment(prisma, booking.id, { status: 'pending', ageSeconds: 5 });

    await expect(start(stubProvider(), booking.reference)).resolves.toStrictEqual({ status: 'in_progress', ourRef: newest.ourRef });
  });

  it('does not block once it is older than the window', async () => {
    const booking = await insertBooking(prisma, world);
    await insertPayment(prisma, booking.id, { status: 'pending', ageSeconds: PAYMENT_ATTEMPT_WINDOW_SECONDS + 5 });
    const provider = stubProvider();

    const result = await start(provider, booking.reference);

    expect(result.status).toBe('started');
    expect(provider.initiated).toHaveLength(1);
    expect((await payments()).map((payment) => payment.status)).toEqual(['pending', 'pending']);
  });

  it.each(['failed', 'refund_due', 'refunded'])('does not block when the earlier attempt is %s', async (status) => {
    const booking = await insertBooking(prisma, world);
    await insertPayment(prisma, booking.id, { status, ageSeconds: 5 });

    await expect(start(stubProvider(), booking.reference)).resolves.toMatchObject({ status: 'started' });
  });

  it('does not block on another booking’s attempt, or on a waiting session fee', async () => {
    const other = await insertBooking(prisma, world);
    await insertPayment(prisma, other.id, { status: 'pending', ageSeconds: 5 });
    const booking = await insertBooking(prisma, world);
    await insertPayment(prisma, booking.id, { status: 'pending', ageSeconds: 5, kind: 'session_fee' });

    await expect(start(stubProvider(), booking.reference)).resolves.toMatchObject({ status: 'started' });
  });

  it('makes one payment when five taps on Pay arrive at once', async () => {
    const booking = await insertBooking(prisma, world);
    const provider = stubProvider({
      initiate: async () => {
        await delay(100);
        return { outcome: 'accepted', providerRef: null };
      },
    });

    const results = await Promise.all(Array.from({ length: 5 }, () => start(provider, booking.reference)));

    const payment = await onlyPayment();
    expect(results.filter((result) => result.status === 'started')).toStrictEqual([{ status: 'started', ourRef: payment.our_ref }]);
    expect(results.filter((result) => result.status === 'in_progress')).toHaveLength(4);
    for (const result of results) expect(result).toMatchObject({ ourRef: payment.our_ref });
    expect(provider.initiated).toHaveLength(1);
    expect(payment.status).toBe('pending');
  });
});
