import type { PrismaClient } from '@prisma/client';
import type pg from 'pg';
import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest';
import { createPrismaClient } from '../db/client.js';
import { connect, firstRow, testDatabaseUrl, truncateAll } from '../test/database.js';
import {
  type PaymentWorld,
  UUID,
  delay,
  insertBooking,
  insertPayment,
  logSink,
  mtnDelivery,
  mtnProvider,
  mtnStatusBody,
  seedWorld,
  stubProvider,
} from '../test/payment-fixtures.js';
import { PAYMENT_ATTEMPT_WINDOW_SECONDS, startBookingFeePayment, startSessionFeePayment } from './initiate.js';
import { type PaymentProvider, PaymentProviderError } from './provider.js';
import { requestSessionFee } from './session-fee.js';
import { receiveWebhook } from './webhooks.js';

/**
 * Starting a booking-fee payment (plan.md Task 16; spec §3.1 step 9;
 * data-model_v2.md §5.11, §6.2, §7.2), against real PostgreSQL with the provider
 * stubbed or pointed at a fake MTN.
 *
 * What is proven: the `payment` row -- `initiated`, `mtn_momo_direct`, its
 * `our_ref` generated by the database -- is committed and visible to another
 * connection BEFORE the provider hears a word, so a provider that throws, or MTN
 * unreachable at the very first HTTP call, still leaves the attempt on record;
 * the provider is handed exactly that `our_ref` and the booking's frozen fee.
 * Accepted, the row is `pending`; refused, unreachable or past the deadline, it
 * is `failed` with the reason, and the booking is untouched -- still
 * `pending_payment`, `hold_expires_at` identical to the millisecond. `amount_rwf`
 * is `booking_fee_rwf` exactly and never changes afterwards, not even when a
 * webhook settles it. A booking already paid, lapsed, expired, closed, free or
 * unknown starts nothing; an attempt still waiting inside the window blocks a
 * second prompt, and one outside it does not; and two taps at once make one
 * payment.
 *
 * The session fee (plan.md Task 18; spec §3.5 step 4, §6.15) takes the same
 * path, with the amount read from `bookingTotals()` as the attempt opens rather
 * than from a frozen column -- except where the photographer has already
 * requested a figure nobody has attempted, which is the figure the client pays.
 * It is owed only by a confirmed or completed booking, and a second session fee
 * after one has succeeded is a new row, which the booking-fee partial unique
 * index does not touch.
 */

let prisma: PrismaClient;
let raw: pg.Client;
let world: PaymentWorld;

beforeAll(async () => {
  prisma = createPrismaClient(testDatabaseUrl());
  raw = connect();
  await raw.connect();
});

afterAll(async () => {
  await truncateAll(raw);
  await prisma.$disconnect();
  await raw.end();
});

beforeEach(async () => {
  await truncateAll(raw);
  world = await seedWorld(prisma);
});

// --- Helpers ----------------------------------------------------------------------------

type PaymentRow = {
  id: string;
  booking_id: string;
  kind: string;
  provider: string;
  our_ref: string;
  provider_ref: string | null;
  method: string | null;
  amount_rwf: number;
  status: string;
  failure_reason: string | null;
  settled_at: Date | null;
};

/** Every payment, through the raw driver: another connection than the one the code under test used. */
async function payments(): Promise<PaymentRow[]> {
  const result = await raw.query<PaymentRow>(
    `SELECT id::text, booking_id::text, kind, provider, our_ref::text, provider_ref, method, amount_rwf, status, failure_reason, settled_at
       FROM payment ORDER BY initiated_at, id`,
  );
  return result.rows;
}

async function onlyPayment(): Promise<PaymentRow> {
  const rows = await payments();
  expect(rows).toHaveLength(1);
  return rows[0] as PaymentRow;
}

type BookingState = { status: string; hold_ms: string | null; confirmed_at: Date | null; access_token_hash: string | null; updated_at: Date };

async function bookingState(reference: string): Promise<BookingState> {
  const result = await raw.query<BookingState>(
    `SELECT status, (extract(epoch FROM hold_expires_at) * 1000000)::bigint::text AS hold_ms, confirmed_at, access_token_hash, updated_at
       FROM booking WHERE reference = $1`,
    [reference],
  );
  return firstRow(result);
}

function start(provider: PaymentProvider, reference: string, options: { timeoutMs?: number; payerPhone?: string } = {}) {
  return startBookingFeePayment(
    { prisma, provider, ...(options.timeoutMs === undefined ? {} : { timeoutMs: options.timeoutMs }) },
    { reference, method: 'momo_mtn', payerPhone: options.payerPhone ?? '+250788123456' },
  );
}

// --- Before the provider ------------------------------------------------------------------

describe('the payment row exists before the provider is called', () => {
  it('is committed as initiated, mtn_momo_direct, with a database-generated our_ref, when the provider is reached -- and the provider then throws', async () => {
    const booking = await insertBooking(prisma, world, { bookingFeeRwf: 19_500 });
    let seenByProvider: PaymentRow[] = [];
    const provider = stubProvider({
      initiate: async (request) => {
        seenByProvider = await payments();
        expect(request.ourRef).toBe(seenByProvider[0]?.our_ref);
        throw new Error('stubbed provider client failure');
      },
    });

    const result = await start(provider, booking.reference);

    expect(seenByProvider).toHaveLength(1);
    expect(seenByProvider[0]).toMatchObject({
      booking_id: booking.id,
      kind: 'booking_fee',
      provider: 'mtn_momo_direct',
      our_ref: expect.stringMatching(UUID),
      amount_rwf: 19_500,
      status: 'initiated',
      provider_ref: null,
      method: null,
      failure_reason: null,
    });
    expect(result).toStrictEqual({ status: 'provider_failed', ourRef: seenByProvider[0]?.our_ref, outcome: 'unavailable' });
    expect(await onlyPayment()).toMatchObject({ id: seenByProvider[0]?.id, status: 'failed', failure_reason: 'provider_unavailable: Error' });
  });

  it('is on record before the real MTN client makes its first HTTP call, which then fails', async () => {
    const booking = await insertBooking(prisma, world);
    const seenAtFirstCall: PaymentRow[][] = [];
    const urls: string[] = [];
    const provider = mtnProvider({
      fetch: (async (input: string) => {
        urls.push(String(input));
        seenAtFirstCall.push(await payments());
        throw new TypeError('fetch failed');
      }) as typeof fetch,
    });

    const result = await start(provider, booking.reference);

    expect(urls).toEqual(['https://mtn.test/collection/token/']);
    expect(seenAtFirstCall[0]).toHaveLength(1);
    expect(seenAtFirstCall[0]?.[0]).toMatchObject({ status: 'initiated', provider: 'mtn_momo_direct', our_ref: expect.stringMatching(UUID) });
    expect(result).toMatchObject({ status: 'provider_failed', outcome: 'unavailable' });
    expect(await onlyPayment()).toMatchObject({
      status: 'failed',
      failure_reason: 'provider_unavailable: MTN MoMo could not be reached: TypeError',
    });
  });

  it('sends MTN the our_ref the database generated, as X-Reference-Id', async () => {
    const booking = await insertBooking(prisma, world);
    const referenceIds: (string | null)[] = [];
    const provider = mtnProvider({
      fetch: (async (input: string, init?: RequestInit) => {
        if (String(input).endsWith('/collection/token/')) return new Response(JSON.stringify({ access_token: 't', expires_in: 3600 }));
        referenceIds.push(new Headers(init?.headers).get('X-Reference-Id'));
        return new Response(null, { status: 202 });
      }) as typeof fetch,
    });

    const result = await start(provider, booking.reference);

    const payment = await onlyPayment();
    expect(result).toStrictEqual({ status: 'started', ourRef: payment.our_ref });
    expect(referenceIds).toEqual([payment.our_ref]);
    expect(payment.status).toBe('pending');
  });

  it('hands the provider the frozen fee, the method, the phone, the kind and the reference', async () => {
    const booking = await insertBooking(prisma, world, { bookingFeeRwf: 23_457 });
    const provider = stubProvider();

    await start(provider, booking.reference, { payerPhone: '+250722000111' });

    expect(provider.initiated).toStrictEqual([
      {
        ourRef: (await onlyPayment()).our_ref,
        amountRwf: 23_457,
        method: 'momo_mtn',
        payerPhone: '+250722000111',
        kind: 'booking_fee',
        bookingReference: booking.reference,
      },
    ]);
  });

  it('records a provider that is not configured as a failed attempt', async () => {
    const booking = await insertBooking(prisma, world);

    const result = await start(mtnProvider({ credentials: false }), booking.reference);

    expect(result).toMatchObject({ status: 'provider_failed', outcome: 'unavailable' });
    expect((await onlyPayment()).failure_reason).toMatch(/^provider_unavailable: MTN MoMo is not configured/);
  });
});

// --- Outcomes -------------------------------------------------------------------------------

describe('what the provider answers', () => {
  it('accepted: the row is pending, the booking untouched', async () => {
    const booking = await insertBooking(prisma, world);
    const before = await bookingState(booking.reference);

    const result = await start(stubProvider(), booking.reference);

    const payment = await onlyPayment();
    expect(result).toStrictEqual({ status: 'started', ourRef: payment.our_ref });
    expect(payment).toMatchObject({ status: 'pending', failure_reason: null, provider_ref: null, amount_rwf: 20_000 });
    expect(await bookingState(booking.reference)).toStrictEqual(before);
  });

  it('accepted with the provider’s own id: it is stored as provider_ref', async () => {
    const booking = await insertBooking(prisma, world);

    await start(stubProvider({ initiate: async () => ({ outcome: 'accepted', providerRef: 'FLW-123' }) }), booking.reference);

    expect(await onlyPayment()).toMatchObject({ status: 'pending', provider_ref: 'FLW-123' });
  });

  it('rejected: the row is failed with the provider’s code, the booking untouched', async () => {
    const booking = await insertBooking(prisma, world);
    const before = await bookingState(booking.reference);

    const result = await start(stubProvider({ initiate: async () => ({ outcome: 'rejected', reason: 'PAYER_NOT_FOUND' }) }), booking.reference);

    const payment = await onlyPayment();
    expect(result).toStrictEqual({ status: 'provider_failed', ourRef: payment.our_ref, outcome: 'rejected' });
    expect(payment).toMatchObject({ status: 'failed', failure_reason: 'PAYER_NOT_FOUND' });
    expect(await bookingState(booking.reference)).toStrictEqual(before);
  });

  it('a PaymentProviderError: failed, quoting our own message', async () => {
    const booking = await insertBooking(prisma, world);

    await start(stubProvider({ initiate: async () => Promise.reject(new PaymentProviderError('MTN MoMo answered 503')) }), booking.reference);

    expect((await onlyPayment()).failure_reason).toBe('provider_unavailable: MTN MoMo answered 503');
  });

  it('any other error: failed, naming the error but never quoting it', async () => {
    const booking = await insertBooking(prisma, world);

    await start(stubProvider({ initiate: async () => Promise.reject(new RangeError('api key sk_live_123 leaked here')) }), booking.reference);

    expect((await onlyPayment()).failure_reason).toBe('provider_unavailable: RangeError');
  });

  it('a thrown non-Error: failed as provider_unavailable: error', async () => {
    const booking = await insertBooking(prisma, world);

    await start(stubProvider({ initiate: async () => Promise.reject('just a string') }), booking.reference);

    expect((await onlyPayment()).failure_reason).toBe('provider_unavailable: error');
  });

  it('stores a rejection reason with a NUL character, and one of 10,000 characters, cut to 500', async () => {
    const nul = await insertBooking(prisma, world);
    await start(stubProvider({ initiate: async () => ({ outcome: 'rejected', reason: `BAD${String.fromCharCode(0)}CODE` }) }), nul.reference);
    const long = await insertBooking(prisma, world);
    await start(stubProvider({ initiate: async () => ({ outcome: 'rejected', reason: 'X'.repeat(10_000) }) }), long.reference);

    const [first, second] = await payments();
    expect(first?.failure_reason).toBe(`BAD${String.fromCharCode(0xfffd)}CODE`);
    expect(second?.failure_reason).toBe('X'.repeat(500));
  });

  it('never moves a row a webhook has already settled while the provider was answering', async () => {
    const accepted = await insertBooking(prisma, world);
    await start(
      stubProvider({
        initiate: async (request) => {
          await raw.query(`UPDATE payment SET status = 'succeeded', settled_at = now() WHERE our_ref = $1`, [request.ourRef]);
          return { outcome: 'accepted', providerRef: 'LATE-REF' };
        },
      }),
      accepted.reference,
    );
    const refused = await insertBooking(prisma, world);
    await start(
      stubProvider({
        initiate: async (request) => {
          await raw.query(`UPDATE payment SET status = 'pending' WHERE our_ref = $1`, [request.ourRef]);
          throw new Error('late failure');
        },
      }),
      refused.reference,
    );

    const [first, second] = await payments();
    expect(first).toMatchObject({ status: 'succeeded', provider_ref: null });
    expect(second).toMatchObject({ status: 'pending', failure_reason: null });
  });
});

// --- Timeout ---------------------------------------------------------------------------------

describe('a provider that does not answer in time', () => {
  it('leaves the row failed with failure_reason provider_timeout, the booking pending_payment and its hold identical', async () => {
    const booking = await insertBooking(prisma, world);
    const before = await bookingState(booking.reference);
    const began = Date.now();

    const result = await start(stubProvider({ initiate: () => new Promise(() => {}) }), booking.reference, { timeoutMs: 50 });

    expect(Date.now() - began).toBeLessThan(5_000);
    const payment = await onlyPayment();
    expect(result).toStrictEqual({ status: 'provider_failed', ourRef: payment.our_ref, outcome: 'unavailable' });
    expect(payment).toMatchObject({ status: 'failed', failure_reason: 'provider_timeout', amount_rwf: 20_000 });

    const after = await bookingState(booking.reference);
    expect(after.status).toBe('pending_payment');
    expect(after.hold_ms).not.toBeNull();
    expect(after.hold_ms).toBe(before.hold_ms);
    expect(after).toStrictEqual(before);
  });

  it('aborts the provider’s signal at the deadline', async () => {
    const booking = await insertBooking(prisma, world);
    let signal: AbortSignal | undefined;

    await start(
      stubProvider({
        initiate: (_request, given) => {
          signal = given;
          return new Promise((_resolve, reject) => given.addEventListener('abort', () => reject(new Error('aborted'))));
        },
      }),
      booking.reference,
      { timeoutMs: 50 },
    );

    expect(signal?.aborted).toBe(true);
    expect((await onlyPayment()).failure_reason).toBe('provider_timeout');
  });

  it('is a timeout with the real MTN client whose HTTP call hangs until aborted', async () => {
    const booking = await insertBooking(prisma, world);
    const provider = mtnProvider({
      fetch: ((_input: string, init?: RequestInit) =>
        new Promise<Response>((_resolve, reject) => {
          init?.signal?.addEventListener('abort', () => reject(new DOMException('This operation was aborted', 'AbortError')));
        })) as typeof fetch,
    });

    const result = await start(provider, booking.reference, { timeoutMs: 50 });

    expect(result).toMatchObject({ status: 'provider_failed', outcome: 'unavailable' });
    expect((await onlyPayment()).failure_reason).toBe('provider_timeout');
    expect((await bookingState(booking.reference)).status).toBe('pending_payment');
  });

  it('stays failed when the provider accepts after the deadline', async () => {
    const booking = await insertBooking(prisma, world);

    await start(
      stubProvider({
        initiate: async () => {
          await delay(200);
          return { outcome: 'accepted', providerRef: null };
        },
      }),
      booking.reference,
      { timeoutMs: 20 },
    );
    await delay(300);

    expect(await onlyPayment()).toMatchObject({ status: 'failed', failure_reason: 'provider_timeout' });
  });

  it('frees the booking to try again at once', async () => {
    const booking = await insertBooking(prisma, world);
    await start(stubProvider({ initiate: () => new Promise(() => {}) }), booking.reference, { timeoutMs: 20 });

    const retry = await start(stubProvider(), booking.reference);

    expect(retry.status).toBe('started');
    expect((await payments()).map((payment) => payment.status)).toEqual(['failed', 'pending']);
  });
});

// --- The amount ------------------------------------------------------------------------------

describe('amount_rwf', () => {
  it('equals booking_fee_rwf exactly, never the package price, a total, or a recomputed 40%', async () => {
    // 40% of 50,000 is 20,000; the frozen fee says otherwise, and wins.
    const booking = await insertBooking(prisma, world, { bookingFeeRwf: 17_777 });

    await start(stubProvider(), booking.reference);

    expect((await onlyPayment()).amount_rwf).toBe(17_777);
  });

  it('is unchanged after the webhook confirms the booking, and after the catalogue price changes', async () => {
    const booking = await insertBooking(prisma, world, { bookingFeeRwf: 19_500 });
    const provider = mtnProvider({
      fetch: (async (input: string) =>
        String(input).endsWith('/collection/token/')
          ? new Response(JSON.stringify({ access_token: 't', expires_in: 3600 }))
          : new Response(null, { status: 202 })) as typeof fetch,
    });
    const started = await start(provider, booking.reference);
    if (started.status !== 'started') throw new Error(`Expected started, got ${started.status}`);

    await prisma.package.update({ where: { id: world.packageId }, data: { priceRwf: 99_000 } });
    const outcome = await receiveWebhook(
      { prisma, log: logSink().log },
      provider,
      mtnDelivery(provider, started.ourRef, mtnStatusBody(started.ourRef, 'SUCCESSFUL', { amount: '19500' })),
    );

    expect(outcome.status).toBe('applied');
    expect(await onlyPayment()).toMatchObject({ status: 'succeeded', amount_rwf: 19_500 });
    expect((await bookingState(booking.reference)).status).toBe('confirmed');
  });

  it('is unchanged after a failure', async () => {
    const booking = await insertBooking(prisma, world, { bookingFeeRwf: 19_500 });
    await start(stubProvider({ initiate: async () => ({ outcome: 'rejected', reason: 'X' }) }), booking.reference);
    expect((await onlyPayment()).amount_rwf).toBe(19_500);
  });
});

// --- Nothing started ------------------------------------------------------------------------

describe('a booking that cannot be paid starts nothing', () => {
  async function expectNothingStarted(provider: ReturnType<typeof stubProvider>, paymentsBefore: number) {
    expect(provider.initiated).toEqual([]);
    expect(await payments()).toHaveLength(paymentsBefore);
  }

  it('not_found for an unknown reference', async () => {
    const provider = stubProvider();
    await expect(start(provider, 'BKY-2610-ZZZZZ')).resolves.toStrictEqual({ status: 'not_found' });
    await expectNothingStarted(provider, 0);
  });

  it('already_paid for a confirmed booking with a succeeded booking fee', async () => {
    const booking = await insertBooking(prisma, world, { status: 'confirmed' });
    await insertPayment(prisma, booking.id, { status: 'succeeded' });
    const provider = stubProvider();

    await expect(start(provider, booking.reference)).resolves.toStrictEqual({ status: 'already_paid' });
    await expectNothingStarted(provider, 1);
  });

  it('already_paid, not hold_expired, even when the booking still holds its slot', async () => {
    const booking = await insertBooking(prisma, world);
    await insertPayment(prisma, booking.id, { status: 'succeeded' });
    const provider = stubProvider();

    await expect(start(provider, booking.reference)).resolves.toStrictEqual({ status: 'already_paid' });
    await expectNothingStarted(provider, 1);
  });

  it('not already_paid for a booking whose only succeeded payment is a session fee', async () => {
    const booking = await insertBooking(prisma, world);
    await insertPayment(prisma, booking.id, { status: 'succeeded', kind: 'session_fee' });

    await expect(start(stubProvider(), booking.reference)).resolves.toMatchObject({ status: 'started' });
  });

  it.each([
    ['a lapsed hold on a booking the sweeper has not reached', { status: 'pending_payment', holdMinutes: -1 }],
    ['a pending_payment booking with no hold at all', { status: 'pending_payment', holdMinutes: null }],
    ['an expired booking', { status: 'expired' }],
    ['a confirmed booking with no succeeded fee', { status: 'confirmed' }],
    ['a completed booking', { status: 'completed' }],
    ['a no-show', { status: 'no_show' }],
    ['a booking the client cancelled', { status: 'cancelled_by_client' }],
    ['a booking the photographer cancelled', { status: 'cancelled_by_admin' }],
    ['an expired booking whose hold column still reads live', { status: 'expired', holdMinutes: 30 }],
  ])('hold_expired for %s', async (_case, seed) => {
    const booking = await insertBooking(prisma, world, seed);
    const provider = stubProvider();

    await expect(start(provider, booking.reference)).resolves.toStrictEqual({ status: 'hold_expired' });
    await expectNothingStarted(provider, 0);
  });

  it('nothing_to_pay for a zero booking fee, which a payment row cannot hold', async () => {
    const booking = await insertBooking(prisma, world, { bookingFeeRwf: 0 });
    const provider = stubProvider();

    await expect(start(provider, booking.reference)).resolves.toStrictEqual({ status: 'nothing_to_pay' });
    await expectNothingStarted(provider, 0);
  });
});

// --- One prompt at a time ---------------------------------------------------------------------

describe('an attempt still waiting on the payer', () => {
  it.each(['initiated', 'pending'])('blocks a new one while %s inside the window, answering its our_ref', async (status) => {
    const booking = await insertBooking(prisma, world);
    const waiting = await insertPayment(prisma, booking.id, { status, ageSeconds: PAYMENT_ATTEMPT_WINDOW_SECONDS - 10 });
    const provider = stubProvider();

    await expect(start(provider, booking.reference)).resolves.toStrictEqual({ status: 'in_progress', ourRef: waiting.ourRef });
    expect(provider.initiated).toEqual([]);
    expect(await payments()).toHaveLength(1);
  });

  it('answers the most recent waiting attempt when there are several', async () => {
    const booking = await insertBooking(prisma, world);
    await insertPayment(prisma, booking.id, { status: 'pending', ageSeconds: 120 });
    const newest = await insertPayment(prisma, booking.id, { status: 'pending', ageSeconds: 5 });

    await expect(start(stubProvider(), booking.reference)).resolves.toStrictEqual({ status: 'in_progress', ourRef: newest.ourRef });
  });

  it('does not block once it is older than the window', async () => {
    const booking = await insertBooking(prisma, world);
    await insertPayment(prisma, booking.id, { status: 'pending', ageSeconds: PAYMENT_ATTEMPT_WINDOW_SECONDS + 5 });
    const provider = stubProvider();

    const result = await start(provider, booking.reference);

    expect(result.status).toBe('started');
    expect(provider.initiated).toHaveLength(1);
    expect((await payments()).map((payment) => payment.status)).toEqual(['pending', 'pending']);
  });

  it.each(['failed', 'refund_due', 'refunded'])('does not block when the earlier attempt is %s', async (status) => {
    const booking = await insertBooking(prisma, world);
    await insertPayment(prisma, booking.id, { status, ageSeconds: 5 });

    await expect(start(stubProvider(), booking.reference)).resolves.toMatchObject({ status: 'started' });
  });

  it('does not block on another booking’s attempt, or on a waiting session fee', async () => {
    const other = await insertBooking(prisma, world);
    await insertPayment(prisma, other.id, { status: 'pending', ageSeconds: 5 });
    const booking = await insertBooking(prisma, world);
    await insertPayment(prisma, booking.id, { status: 'pending', ageSeconds: 5, kind: 'session_fee' });

    await expect(start(stubProvider(), booking.reference)).resolves.toMatchObject({ status: 'started' });
  });

  it('makes one payment when five taps on Pay arrive at once', async () => {
    const booking = await insertBooking(prisma, world);
    const provider = stubProvider({
      initiate: async () => {
        await delay(100);
        return { outcome: 'accepted', providerRef: null };
      },
    });

    const results = await Promise.all(Array.from({ length: 5 }, () => start(provider, booking.reference)));

    const payment = await onlyPayment();
    expect(results.filter((result) => result.status === 'started')).toStrictEqual([{ status: 'started', ourRef: payment.our_ref }]);
    expect(results.filter((result) => result.status === 'in_progress')).toHaveLength(4);
    for (const result of results) expect(result).toMatchObject({ ourRef: payment.our_ref });
    expect(provider.initiated).toHaveLength(1);
    expect(payment.status).toBe('pending');
  });
});

// --- The session fee ---------------------------------------------------------------------------

/** Adds a post-shoot add-on, which is what makes more money outstanding after the shoot. */
async function addPostShootAddon(bookingId: string, amountRwf: number): Promise<void> {
  await prisma.bookingAddon.create({
    data: { bookingId, addonId: world.ownAddonId, nameSnapshot: 'Extra prints', unitPriceRwf: amountRwf, amountRwf, stage: 'post_shoot' },
  });
}

function startSession(
  provider: PaymentProvider,
  booking: { id: string; reference: string },
  options: { timeoutMs?: number } = {},
) {
  return startSessionFeePayment(
    { prisma, provider, ...(options.timeoutMs === undefined ? {} : { timeoutMs: options.timeoutMs }) },
    {
      bookingId: booking.id,
      reference: booking.reference,
      method: 'momo_mtn',
      payerPhone: '+250788123456',
    },
  );
}

/** A confirmed booking, fee paid: 40,000 package + 10,000 add-on, 20,000 collected, 30,000 owed. */
async function owingBooking(status = 'confirmed') {
  const booking = await insertBooking(prisma, world, { status });
  await insertPayment(prisma, booking.id, { status: 'succeeded', amountRwf: 20_000, ageSeconds: 600 });
  return booking;
}

describe('the session-fee row exists before the provider is called', () => {
  it('is committed as initiated, on this booking, with the outstanding amount, when the provider then throws', async () => {
    const booking = await owingBooking();
    let seenByProvider: PaymentRow[] = [];
    const provider = stubProvider({
      initiate: async (request) => {
        seenByProvider = await payments();
        expect(request.ourRef).toBe(seenByProvider.find((row) => row.kind === 'session_fee')?.our_ref);
        throw new Error('stubbed provider client failure');
      },
    });

    const result = await startSession(provider, booking);

    const opened = seenByProvider.find((row) => row.kind === 'session_fee');
    expect(opened).toMatchObject({
      booking_id: booking.id,
      kind: 'session_fee',
      provider: 'mtn_momo_direct',
      our_ref: expect.stringMatching(UUID),
      amount_rwf: 30_000,
      status: 'initiated',
      provider_ref: null,
      failure_reason: null,
    });
    expect(result).toStrictEqual({ status: 'provider_failed', ourRef: opened?.our_ref, outcome: 'unavailable' });
    expect((await payments()).find((row) => row.kind === 'session_fee')).toMatchObject({ status: 'failed' });
  });

  it('hands the provider the amount, the method, the phone, the kind and the reference', async () => {
    const booking = await owingBooking();
    await addPostShootAddon(booking.id, 15_000);
    const provider = stubProvider();

    await startSession(provider, booking);

    expect(provider.initiated).toStrictEqual([
      {
        ourRef: (await payments()).find((row) => row.kind === 'session_fee')?.our_ref,
        amountRwf: 45_000,
        method: 'momo_mtn',
        payerPhone: '+250788123456',
        kind: 'session_fee',
        bookingReference: booking.reference,
      },
    ]);
  });
});

describe('the session fee amount', () => {
  it('is the outstanding amount, post-shoot add-ons included (data-model_v2.md §6.1)', async () => {
    const booking = await owingBooking();
    await addPostShootAddon(booking.id, 15_000);

    await startSession(stubProvider(), booking);

    expect((await payments()).find((row) => row.kind === 'session_fee')?.amount_rwf).toBe(45_000);
  });

  it('counts only payments that succeeded: a failed attempt does not reduce it', async () => {
    const booking = await owingBooking();
    await insertPayment(prisma, booking.id, { status: 'failed', kind: 'session_fee', amountRwf: 30_000, ageSeconds: 500 });
    await insertPayment(prisma, booking.id, { status: 'refund_due', kind: 'session_fee', amountRwf: 5_000, ageSeconds: 400 });

    await startSession(stubProvider(), booking);

    expect((await payments()).at(-1)).toMatchObject({ kind: 'session_fee', amount_rwf: 30_000 });
  });

  it('reuses the photographer own request row and its frozen amount, rather than repricing it', async () => {
    const booking = await owingBooking('completed');
    const requested = await insertPayment(prisma, booking.id, {
      status: 'initiated',
      kind: 'session_fee',
      amountRwf: 30_000,
      ageSeconds: PAYMENT_ATTEMPT_WINDOW_SECONDS + 60,
    });
    // The photographer adds an add-on after asking: the client still pays what they were asked.
    await addPostShootAddon(booking.id, 15_000);
    const provider = stubProvider();

    const result = await startSession(provider, booking);

    expect(result).toStrictEqual({ status: 'started', ourRef: requested.ourRef });
    expect(provider.initiated).toStrictEqual([expect.objectContaining({ ourRef: requested.ourRef, amountRwf: 30_000 })]);
    const rows = await payments();
    expect(rows.filter((row) => row.kind === 'session_fee')).toHaveLength(1);
    expect(rows.find((row) => row.id === requested.id)).toMatchObject({ status: 'pending', amount_rwf: 30_000 });
  });

  it('never attempts a row recorded against another provider (spec §6.18): it opens its own', async () => {
    const booking = await owingBooking();
    const foreign = await insertPayment(prisma, booking.id, {
      status: 'initiated',
      kind: 'session_fee',
      amountRwf: 30_000,
      provider: 'flutterwave',
      ageSeconds: PAYMENT_ATTEMPT_WINDOW_SECONDS + 60,
    });

    const result = await startSession(stubProvider(), booking);

    expect(result).toMatchObject({ status: 'started' });
    if (result.status !== 'started') throw new Error('unreachable');
    expect(result.ourRef).not.toBe(foreign.ourRef);
    expect((await payments()).filter((row) => row.kind === 'session_fee')).toHaveLength(2);
  });

  it('is never written again once the provider has been asked', async () => {
    const booking = await owingBooking();
    await startSession(stubProvider(), booking);
    const before = (await payments()).find((row) => row.kind === 'session_fee');

    await addPostShootAddon(booking.id, 15_000);

    expect((await payments()).find((row) => row.kind === 'session_fee')?.amount_rwf).toBe(before?.amount_rwf);
  });
});

describe('a session fee that cannot be started', () => {
  it('not_found for a booking id nothing matches', async () => {
    const provider = stubProvider();

    await expect(
      startSession(provider, { id: '00000000-0000-4000-8000-000000000000', reference: 'BKY-2610-ZZZZZ' }),
    ).resolves.toStrictEqual({ status: 'not_found' });
    expect(provider.initiated).toEqual([]);
    expect(await payments()).toEqual([]);
  });

  it('nothing_to_pay once the shoot is paid in full', async () => {
    const booking = await owingBooking();
    await insertPayment(prisma, booking.id, { status: 'succeeded', kind: 'session_fee', amountRwf: 30_000, ageSeconds: 500 });
    const provider = stubProvider();

    await expect(startSession(provider, booking)).resolves.toStrictEqual({ status: 'nothing_to_pay' });
    expect(provider.initiated).toEqual([]);
    expect(await payments()).toHaveLength(2);
  });

  it.each(['pending_payment', 'expired', 'no_show', 'cancelled_by_client', 'cancelled_by_admin'])(
    'nothing_to_pay for a %s booking, which owes nothing (data-model_v2.md §6.1)',
    async (status) => {
      const booking = await owingBooking(status);
      const provider = stubProvider();

      await expect(startSession(provider, booking)).resolves.toStrictEqual({ status: 'nothing_to_pay' });
      expect(provider.initiated).toEqual([]);
      expect((await payments()).filter((row) => row.kind === 'session_fee')).toEqual([]);
    },
  );
});

describe('a session-fee attempt still waiting on the payer', () => {
  it('blocks a new one while pending, answering its our_ref', async () => {
    const booking = await owingBooking();
    const waiting = await insertPayment(prisma, booking.id, { status: 'pending', kind: 'session_fee', amountRwf: 30_000, ageSeconds: 30 });
    const provider = stubProvider();

    await expect(startSession(provider, booking)).resolves.toStrictEqual({ status: 'in_progress', ourRef: waiting.ourRef });
    expect(provider.initiated).toEqual([]);
    expect((await payments()).filter((row) => row.kind === 'session_fee')).toHaveLength(1);
  });

  it('blocks a new one while an initiated attempt could still be at the provider', async () => {
    // The provider is called outside the transaction, so a row this young may
    // be a call that has not answered yet: prompting again pays it twice.
    const booking = await owingBooking();
    const waiting = await insertPayment(prisma, booking.id, {
      status: 'initiated',
      kind: 'session_fee',
      amountRwf: 30_000,
      ageSeconds: 5,
    });

    await expect(startSession(stubProvider(), booking)).resolves.toStrictEqual({ status: 'in_progress', ourRef: waiting.ourRef });
  });

  it('pays an older initiated row instead, because that is the photographer’s request (Task 20)', async () => {
    // Nothing is calling a provider about a row this old. It is the request
    // made from the admin screen, waiting for the client to pay what it froze.
    const booking = await owingBooking();
    const requested = await insertPayment(prisma, booking.id, {
      status: 'initiated',
      kind: 'session_fee',
      amountRwf: 30_000,
      ageSeconds: PAYMENT_ATTEMPT_WINDOW_SECONDS - 10,
    });
    const provider = stubProvider();

    await expect(startSession(provider, booking)).resolves.toStrictEqual({ status: 'started', ourRef: requested.ourRef });
    // The same row, at the amount it was asked for: no second bill.
    expect((await payments()).filter((row) => row.kind === 'session_fee')).toHaveLength(1);
    expect(provider.initiated).toHaveLength(1);
  });

  it("blocks a new one while pending inside the window", async () => {
    const booking = await owingBooking();
    const waiting = await insertPayment(prisma, booking.id, {
      status: 'pending',
      kind: 'session_fee',
      amountRwf: 30_000,
      ageSeconds: PAYMENT_ATTEMPT_WINDOW_SECONDS - 10,
    });

    await expect(startSession(stubProvider(), booking)).resolves.toStrictEqual({ status: 'in_progress', ourRef: waiting.ourRef });
  });

  /**
   * A `pending` attempt nothing ever settles -- a webhook lost, a payer who
   * walked away -- must not lock the client out of their own payment control
   * for good. Past the window a fresh attempt opens, exactly as the booking
   * fee's does.
   */
  it("opens a new attempt when the pending one is older than the window", async () => {
    const booking = await owingBooking();
    const stuck = await insertPayment(prisma, booking.id, {
      status: 'pending',
      kind: 'session_fee',
      amountRwf: 30_000,
      ageSeconds: 90 * 24 * 3_600,
    });
    const provider = stubProvider();

    const result = await startSession(provider, booking);

    expect(result.status).toBe('started');
    expect(result).not.toMatchObject({ ourRef: stuck.ourRef });
    expect(provider.initiated).toHaveLength(1);
    const sessionFees = (await payments()).filter((row) => row.kind === 'session_fee');
    expect(sessionFees).toHaveLength(2);
    // The stale one is left exactly as it was: only its own webhook settles it.
    expect(sessionFees.find((row) => row.our_ref === stuck.ourRef)).toMatchObject({ status: 'pending' });
  });

  it('answers the most recent session-fee attempt when there are several', async () => {
    const booking = await owingBooking();
    await insertPayment(prisma, booking.id, { status: 'failed', kind: 'session_fee', amountRwf: 30_000, ageSeconds: 500 });
    const newest = await insertPayment(prisma, booking.id, { status: 'pending', kind: 'session_fee', amountRwf: 30_000, ageSeconds: 10 });

    await expect(startSession(stubProvider(), booking)).resolves.toStrictEqual({ status: 'in_progress', ourRef: newest.ourRef });
  });

  it('is not blocked by another booking attempt, or by a waiting booking fee', async () => {
    const other = await owingBooking();
    await insertPayment(prisma, other.id, { status: 'pending', kind: 'session_fee', amountRwf: 30_000, ageSeconds: 10 });
    const booking = await owingBooking();
    await insertPayment(prisma, booking.id, { status: 'pending', kind: 'booking_fee', amountRwf: 20_000, ageSeconds: 10 });

    await expect(startSession(stubProvider(), booking)).resolves.toMatchObject({ status: 'started' });
  });

  it.each(['failed', 'refund_due', 'refunded'])('is not blocked when the newest attempt is %s', async (status) => {
    const booking = await owingBooking();
    await insertPayment(prisma, booking.id, { status, kind: 'session_fee', amountRwf: 5_000, ageSeconds: 10 });

    await expect(startSession(stubProvider(), booking)).resolves.toMatchObject({ status: 'started' });
  });

  it('makes one payment when five taps on Pay arrive at once', async () => {
    const booking = await owingBooking();
    const provider = stubProvider({
      initiate: async () => {
        await delay(100);
        return { outcome: 'accepted', providerRef: null };
      },
    });

    const results = await Promise.all(Array.from({ length: 5 }, () => startSession(provider, booking)));

    expect((await payments()).filter((row) => row.kind === 'session_fee')).toHaveLength(1);
    expect(results.filter((result) => result.status === 'started')).toHaveLength(1);
    expect(results.filter((result) => result.status === 'in_progress')).toHaveLength(4);
    expect(provider.initiated).toHaveLength(1);
  });
});

describe('a provider that will not start the session fee', () => {
  it('leaves the row failed with provider_timeout and the booking untouched', async () => {
    const booking = await owingBooking();
    const before = await bookingState(booking.reference);

    const result = await startSession(stubProvider({ initiate: () => new Promise(() => {}) }), booking, { timeoutMs: 50 });

    const session = (await payments()).find((row) => row.kind === 'session_fee');
    expect(result).toStrictEqual({ status: 'provider_failed', ourRef: session?.our_ref, outcome: 'unavailable' });
    expect(session).toMatchObject({ status: 'failed', failure_reason: 'provider_timeout', amount_rwf: 30_000 });
    expect(await bookingState(booking.reference)).toStrictEqual(before);
  });

  it('records a refusal with the provider own code, and frees the client to try again at once', async () => {
    const booking = await owingBooking();
    let fail = true;
    const provider = stubProvider({
      initiate: async () => (fail ? { outcome: 'rejected', reason: 'PAYER_NOT_FOUND' } : { outcome: 'accepted', providerRef: null }),
    });

    await expect(startSession(provider, booking)).resolves.toMatchObject({ status: 'provider_failed', outcome: 'rejected' });
    expect((await payments()).find((row) => row.kind === 'session_fee')).toMatchObject({ status: 'failed', failure_reason: 'PAYER_NOT_FOUND' });

    fail = false;
    await expect(startSession(provider, booking)).resolves.toMatchObject({ status: 'started' });
    expect((await payments()).filter((row) => row.kind === 'session_fee').map((row) => row.status)).toEqual(['failed', 'pending']);
  });
});

describe('a second session fee after one succeeded (spec §6.15)', () => {
  it('is a new row, not an edit of the settled one, and no unique index refuses it', async () => {
    const booking = await owingBooking('completed');
    const first = await insertPayment(prisma, booking.id, { status: 'succeeded', kind: 'session_fee', amountRwf: 30_000, ageSeconds: 500 });
    await addPostShootAddon(booking.id, 15_000);

    const result = await startSession(stubProvider(), booking);

    expect(result).toMatchObject({ status: 'started' });
    const sessionFees = (await payments()).filter((row) => row.kind === 'session_fee');
    expect(sessionFees).toHaveLength(2);
    expect(sessionFees.find((row) => row.id === first.id)).toMatchObject({ status: 'succeeded', amount_rwf: 30_000 });
    expect(sessionFees.find((row) => row.id !== first.id)).toMatchObject({ status: 'pending', amount_rwf: 15_000 });
  });

  it('lets both session fees succeed while the booking fee partial unique index still holds', async () => {
    const booking = await owingBooking('completed');
    await insertPayment(prisma, booking.id, { status: 'succeeded', kind: 'session_fee', amountRwf: 30_000, ageSeconds: 500 });
    await addPostShootAddon(booking.id, 15_000);
    const started = await startSession(stubProvider(), booking);
    if (started.status !== 'started') throw new Error(`Expected started, got ${started.status}`);

    await raw.query(`UPDATE payment SET status = 'succeeded', settled_at = now() WHERE our_ref = $1`, [started.ourRef]);

    expect((await payments()).filter((row) => row.kind === 'session_fee' && row.status === 'succeeded')).toHaveLength(2);
    // And a second succeeded booking fee is still impossible.
    await expect(
      raw.query(
        `INSERT INTO payment (booking_id, kind, provider, amount_rwf, status) VALUES ($1, 'booking_fee', 'mtn_momo_direct', 1, 'succeeded')`,
        [booking.id],
      ),
    ).rejects.toMatchObject({ code: '23505' });
  });
});

// --- The photographer asks, the client pays (plan.md Task 20, spec §3.5 steps 3-4) ------------------

/**
 * The two halves joined. `requestSessionFee` writes an `initiated` row for the
 * amount outstanding when he asks and freezes it; `startSessionFeePayment`
 * finds that row and pays it, at that amount and against that `our_ref`,
 * whatever the add-ons have done since.
 *
 * The rows are aged first, and deliberately so: an `initiated` session fee
 * younger than `CALL_IN_FLIGHT_SECONDS` (30 s) is indistinguishable from an
 * attempt whose provider call has not answered, and prompting again there is
 * how a fee gets paid twice. A photographer's request the client pays seconds
 * later is not a case that exists -- the client has to read the email first.
 */
describe('a request made from the admin screen, then paid by the client', () => {
  const ASK_CLOCK = new Date('2026-10-01T06:00:00Z');

  /** Past the in-flight window, so the request reads as a request rather than a call in progress. */
  async function ageSessionFees(): Promise<void> {
    await prisma.$executeRaw`UPDATE payment SET initiated_at = initiated_at - interval '5 minutes' WHERE kind = 'session_fee'`;
  }

  async function ask(bookingId: string, providerId: 'mtn_momo_direct' | 'flutterwave' = 'mtn_momo_direct') {
    const result = await requestSessionFee({ prisma, providerId, now: () => ASK_CLOCK }, bookingId);
    if (result.status !== 'ok') throw new Error(`Expected the request to be made, got ${result.status}`);
  }

  it('calls the provider with the frozen amount and the same our_ref the request opened', async () => {
    const booking = await owingBooking('completed');
    await ask(booking.id);
    const requested = (await payments()).find((row) => row.kind === 'session_fee');
    // He remembers another add-on after asking: the client still pays what they were asked.
    await addPostShootAddon(booking.id, 15_000);
    await ageSessionFees();
    const provider = stubProvider();

    const result = await startSession(provider, booking);

    expect(result).toStrictEqual({ status: 'started', ourRef: requested?.our_ref });
    expect(provider.initiated).toStrictEqual([
      {
        ourRef: requested?.our_ref,
        amountRwf: 30_000,
        method: 'momo_mtn',
        payerPhone: '+250788123456',
        kind: 'session_fee',
        bookingReference: booking.reference,
      },
    ]);
    // One row, at the amount asked for, now waiting on the payer.
    const sessionFees = (await payments()).filter((row) => row.kind === 'session_fee');
    expect(sessionFees).toHaveLength(1);
    expect(sessionFees[0]).toMatchObject({ id: requested?.id, amount_rwf: 30_000, status: 'pending' });
  });

  it('is payable the instant it is asked for, because an ask is not a call in flight', async () => {
    // The email arrives in seconds and the client taps Pay: nothing is in
    // progress, and the row they are paying is the one the ask opened.
    const booking = await owingBooking('completed');
    await ask(booking.id);
    const requested = (await payments()).find((row) => row.kind === 'session_fee');
    const provider = stubProvider();

    const result = await startSession(provider, booking);

    expect(result).toStrictEqual({ status: 'started', ourRef: requested?.our_ref });
    expect(provider.initiated).toStrictEqual([expect.objectContaining({ amountRwf: 30_000 })]);
    expect((await payments()).filter((row) => row.kind === 'session_fee')).toHaveLength(1);
  });

  it('still answers in_progress for an attempt nobody asked for, which may be a call in flight', async () => {
    // Same age, no ask behind it: this is a second tap, and a second prompt
    // on the same phone is how one fee gets paid twice.
    const booking = await owingBooking('completed');
    const tapped = await insertPayment(prisma, booking.id, {
      status: 'initiated',
      kind: 'session_fee',
      amountRwf: 30_000,
      ageSeconds: 5,
    });
    const provider = stubProvider();

    const result = await startSession(provider, booking);

    expect(result).toStrictEqual({ status: 'in_progress', ourRef: tapped.ourRef });
    expect(provider.initiated).toEqual([]);
    expect((await payments()).filter((row) => row.kind === 'session_fee')).toHaveLength(1);
  });

  it('lets a newer request supersede an older one: the client pays the latest amount asked for', async () => {
    const booking = await owingBooking('completed');
    await ask(booking.id);
    const first = (await payments()).find((row) => row.kind === 'session_fee');
    await addPostShootAddon(booking.id, 15_000);
    await ask(booking.id);
    const rows = (await payments()).filter((row) => row.kind === 'session_fee');
    const second = rows.find((row) => row.id !== first?.id);
    expect(rows).toHaveLength(2);
    // Distinctly aged, so "the newest request" is a fact and not a tie.
    await prisma.$executeRaw`UPDATE payment SET initiated_at = now() - interval '10 minutes' WHERE id = ${first?.id}::uuid`;
    await prisma.$executeRaw`UPDATE payment SET initiated_at = now() - interval '5 minutes' WHERE id = ${second?.id}::uuid`;
    const provider = stubProvider();

    const result = await startSession(provider, booking);

    expect(result).toStrictEqual({ status: 'started', ourRef: second?.our_ref });
    expect(provider.initiated).toStrictEqual([expect.objectContaining({ ourRef: second?.our_ref, amountRwf: 45_000 })]);
    // The superseded ask is left exactly as it was: only its own webhook settles it.
    expect((await payments()).find((row) => row.id === first?.id)).toMatchObject({ status: 'initiated', amount_rwf: 30_000 });
  });

  it('opens its own row when the request was recorded against another provider (spec §6.18)', async () => {
    const booking = await owingBooking('completed');
    await ask(booking.id, 'flutterwave');
    const foreign = (await payments()).find((row) => row.kind === 'session_fee');
    await ageSessionFees();

    const result = await startSession(stubProvider(), booking);

    expect(result).toMatchObject({ status: 'started' });
    if (result.status !== 'started') throw new Error('unreachable');
    expect(result.ourRef).not.toBe(foreign?.our_ref);
    expect((await payments()).filter((row) => row.kind === 'session_fee')).toHaveLength(2);
  });

  it('settles the frozen amount, leaving the booking paid in full for what was asked', async () => {
    const booking = await owingBooking('completed');
    await ask(booking.id);
    await ageSessionFees();
    const started = await startSession(stubProvider(), booking);
    if (started.status !== 'started') throw new Error(`Expected started, got ${started.status}`);

    await raw.query(`UPDATE payment SET status = 'succeeded', settled_at = now() WHERE our_ref = $1`, [started.ourRef]);

    const sessionFee = (await payments()).find((row) => row.kind === 'session_fee');
    expect(sessionFee).toMatchObject({ amount_rwf: 30_000, status: 'succeeded' });
    // And a second attempt now has nothing to collect.
    await expect(startSession(stubProvider(), booking)).resolves.toStrictEqual({ status: 'nothing_to_pay' });
  });
});
