/**
 * The payment provider seam (plan.md Task 16; spec §4.3): initiate, verify,
 * read a webhook, look up a status. MTN MoMo direct implements it now and
 * Flutterwave with Task 25; which one takes new payments is configuration
 * (`PAYMENT_PROVIDER`), never a branch in business logic.
 *
 * A provider speaks its own dialect at the edges and ours in the middle: what
 * it reports is normalised here to `pending`, `succeeded` or `failed`. It never
 * reports `refund_due` or `refunded` -- those are the photographer's
 * (data-model_v2.md §7.3) -- and it never touches the database.
 */

/** `payment_provider_allowed`. */
export const PAYMENT_PROVIDERS = ['mtn_momo_direct', 'flutterwave'] as const;
export type PaymentProviderId = (typeof PAYMENT_PROVIDERS)[number];

/** `payment_method_allowed`. */
export const PAYMENT_METHODS = ['momo_mtn', 'momo_airtel', 'card'] as const;
export type PaymentMethod = (typeof PAYMENT_METHODS)[number];

/** `payment_status_allowed`, in the order of data-model_v2.md §7.2. */
export const PAYMENT_STATUSES = ['initiated', 'pending', 'succeeded', 'failed', 'refund_due', 'refunded'] as const;
export type PaymentStatus = (typeof PAYMENT_STATUSES)[number];

/**
 * Statuses no provider event may move a payment out of (data-model_v2.md §7.3
 * step 4). `refund_due` is on the list too: it is only ever reached from
 * `succeeded`, and from there only the photographer moves it.
 */
export const SETTLED_PAYMENT_STATUSES = ['succeeded', 'failed', 'refunded', 'refund_due'] as const satisfies readonly PaymentStatus[];

export type PaymentKind = 'booking_fee' | 'session_fee';

/** What a provider may assert about a payment. */
export type ReportedStatus = 'pending' | 'succeeded' | 'failed';

export type InitiatePaymentRequest = {
  /** Generated by the database before this call (data-model_v2.md fix #3). */
  ourRef: string;
  /** Whole RWF, frozen on the payment row. */
  amountRwf: number;
  method: PaymentMethod;
  /** E.164 as `normalizePhone` returns it, or the digits typed. */
  payerPhone: string;
  kind: PaymentKind;
  bookingReference: string;
};

export type InitiatePaymentResult =
  /** The provider took the request and is waiting on the payer. */
  | { outcome: 'accepted'; providerRef: string | null }
  /** The provider answered and refused. `reason` is a short code, never free text from the payer. */
  | { outcome: 'rejected'; reason: string };

/** One inbound delivery, exactly as it arrived. */
export type WebhookDelivery = {
  /** The bytes, before any JSON parser has seen them. */
  rawBody: Buffer;
  headers: Record<string, string | string[] | undefined>;
  /** Route parameters: MTN's callback URL carries our reference and its signature. */
  params: Record<string, string | undefined>;
};

/** A provider event in our vocabulary (data-model_v2.md §5.12). */
export type ProviderEvent = {
  /** Unique per provider; a repeat is a duplicate delivery. */
  eventId: string;
  eventType: string;
  ourRef: string | null;
  providerRef: string | null;
  /** Null when the event asserts nothing we understand. */
  reportedStatus: ReportedStatus | null;
  method: PaymentMethod | null;
  /** A short code for a failure, when the provider gave one. */
  failureReason: string | null;
  /** The amount the provider says moved, in whole units, when it says. */
  amount: number | null;
};

export interface PaymentProvider {
  readonly id: PaymentProviderId;
  /** What the pay page may offer (spec §6.19). Nothing else is rendered. */
  readonly methods: readonly PaymentMethod[];
  /** False when credentials are missing: initiation then fails at once, recorded. */
  readonly configured: boolean;

  /** Throws when the provider cannot be reached or answers unusably. */
  initiate(request: InitiatePaymentRequest, signal: AbortSignal): Promise<InitiatePaymentResult>;

  /** Asks the provider where a payment stands. Null when it has never heard of it. */
  lookupStatus(ourRef: string, signal: AbortSignal): Promise<{ event: ProviderEvent; payload: unknown } | null>;

  /** Step 1 of §7.3. Must not throw. */
  verifyWebhook(delivery: WebhookDelivery): boolean;

  /** The event a delivery describes, or null when it describes none this provider recognises. Must not throw. */
  parseWebhook(delivery: WebhookDelivery): ProviderEvent | null;
}

/** The provider was unreachable, timed out or answered in a way no retry of ours can read. */
export class PaymentProviderError extends Error {
  override readonly name = 'PaymentProviderError';
}
